### PR TITLE
Ports Blueshield from Paradise

### PR DESCRIPTION
**Pull request by Birdtalon**
Ports necessary code for Blueshield from Paradise.

Issues

- The gun needs looking at as I have no idea how the sprite overlays work.
- I haven't bothered with the skirt or the hoodie.
- No jacksandals 😢

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Feel free to just give him a random gun and we'll bother with adding the revolver later.

**Comment by Birdtalon** [comment]
The gun works for now, it just looks manky because of the overlay that's all.

**Comment by SamHPurp** [comment]
@FlattestGuitar if you're happy this can go

**Comment by FlattestGuitar** [comment]
Might as well.

We'll polish the Blue's gun later.

**Pull request merged**
