### PR TITLE
Removes 'memey' plants from botany

### PR DESCRIPTION
**Pull request by owenowen212**
Removes a number of plants from Botany that are considered too 'memey' for the server.

**This is a port of a PR for Planetfall so I'll leave the original PR description below:**

A full list of plants removed is as follows:
### Removed plants/seeds:

Bluespace bananas
Mimana bananas
Rainbowweed
Lifeweed
Omegaweed
Deathweed
Combustible lemons
Snapcorn
Novaflowers
Carpet
Holymelons
Cherrybombs
Gatfruit
Walking mushrooms
Killer tomatoes
Blue tomatoes
Bluespace tomatoes
### Unremoved though questionable:

Blood tomatoes
Blumpkins
Shadowshrooms
Glowcaps
Kudzu
Moonflowers
Egg-plants
Meatwheat
Glowberries
Gold apples

### Other notes:

- Removed mimana bread.
- Changes required ingredient in melonkeg recipe from a holymelon to a regular watermelon.
- Removed references to removed seeds/plants in loot crates and other maps.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Now that we're back on the station, I'm wondering if stuff like carpet is ok to stay.

Not sure, what do you think?

**Comment by Birdtalon** [comment]
After discussion on Discord I've changed my mind and I think we can safely leave;

Lifeweed
Holymelons
Walking mushrooms
Killer tomatoes
Blue Tomatoes?

**Comment by SamHPurp** [comment]
Ratings out of 5. 5 being "REMOVE, holy shit remove jesus christ..." 1 being "I'd prefer we keep these" 2 & are a preference but won't mind if people disagree and it stays/goes.

- Bluespace bananas - 4
- Mimana bananas - 4
- Rainbowweed - 3
- Lifeweed - 3
- Omegaweed - 3
- Deathweed - 3
- Combustible lemons - 5
- Snapcorn -3
- Novaflowers - 4
- Carpet - 3
- Holymelons -3
- Cherrybombs -5
- Gatfruit - 5
- Walking mushrooms - 3
- Killer tomatoes - 3
- Blue tomatoes - 4
- Bluespace tomatoes - 5

**Comment by Birdtalon** [comment]
As you didn't use 1 or 2, they may as well be rating out of 3 👀

**Comment by SamHPurp** [comment]
@Birdtalon Nah, by doing it out of five, I leave the door open for 1 and 2...

**Comment by FlattestGuitar** [comment]
I gotta be honest. I see no point in removing the vast majority of those. We're not trying to become Bay 2.0, some degree of cartoon-ish unseriousness is good for us. The only things I have an issue with is the bluespace tomatoes, blue tomatoes and gatfruits, the rest seems perfectly fine to me.
- Killer tomatoes are hilariously lethal to whoever makes them in the first place.
- Combustible lemons are just IEDs.
- Cherry bombs are just grenades with smoke with the option to mix other reagents inside; nothing science couldn't make ten times better.

What is wrong with things like snapcorn or omega weed, I do not understand.

**Comment by SamHPurp** [comment]
@FlattestGuitar The issue with combustible lemons is that you can max potency them, and grow a couple of hundred which all fit in your massive bags. They're pretty toxic on TG station when I've seen them used.

**Comment by FlattestGuitar** [comment]
Well, I trust your judgement if you think you've got enough experience with them. I haven't seen them in action.

We should not strive to remove the "memey" stuff as long as it's funny and fits the universe, in my opinion. MRP isn't supposed to be this strict in my eyes.

**Comment by SamHPurp** [comment]
@owenowen212 able to have a dialogue on these, or shall I close?

**Comment by SamHPurp** [comment]
There are still elements of this I'd like to implement in the future, but author is AWOL.

**Pull request closed without merging**
